spring:
  application:
    name: reactive-java-project
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bikini-bottom
    username: spanch
    password: bob
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: debug
